<?php
/**
 * Slider items template
 *
 * @var $block \Dotsquares\ProductSlider\Block\Slider\Items
 */
?>
<?php use Magento\Framework\App\Action\Action; ?>
<?php
$_items = $block->getSliderProductsCollection();
$sliderId = $block->getSliderDisplayId();

// slider config
$slider = $block->getSlider();
$showWishlist = $slider->getDisplayWishlist();
$showCompare = $slider->getDisplayCompare();
$showCart = $slider->getDisplayCart();
$enableAjaxcart = $slider->getEnableAjaxcart();
$navigation_enable = $slider->getNavigationEnable();
$pagination_enable = $slider->getPaginationEnable();

$image = 'category_page_grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$viewMode = 'grid';
$class = $slider->getType();
$type = "";
?>
<?php if (count($_items) == 0): ?>
    <p class="message note"><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></p>    
<?php else:

  ?>
    <div class="ds-prodslider block slider-type-<?= $block->escapeHtml($class); ?> 
        ds-prodslider-t"
            <?= $slider->getRtl() ? 'dir="rtl" ' : "" ?> >
        <?php if ($slider->getDisplayTitle()): ?>
        <div class="title-block">
         <h2 id="block-<?= $block->escapeHtml($class) ?>-heading" role="heading" aria-level="2">
            <?= $block->escapeHtml($slider->getTitle()) ?>
         </h2>

         <div class="small-divider"></div>
         <p class="ds-info"> <?= $block->escapeHtml($slider->getDescription()) ?></p>
         <!-- <h1>description</h1> -->
        </div>
        <?php endif ?>
      <div class="content-block slider-list"
        aria-labelledby="block-<?= $block->escapeHtml($class) ?>-heading">
        <?php if (!empty($_items)): ?>
        <div class="products wrapper grid products-grid products-<?= $block->escapeHtml($type); ?>">
        <ol class="products list items product-slider<?= $block->escapeHtml($sliderId) ?> owl-carousel owl-theme">
            <?php foreach ($_items as $collection): ?>
                <?php $iterator = 1; ?>
                <?php foreach ($collection as $_item): 
                 
                  ?>

                    <?= ($iterator++ == 1)
                    ? '<li class="item product ds-product-item">' : '</li><li class="item product ds-product-item">' ?>
        <div class="ds-product-item-info 
            product-item-info<?= $slider->getGrid() ? '' : '-'. $block->escapeHtml($class) ?>">
        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" 
        class="product photo product-item-photo">
                    <?= $block->getImage($_item, $image)->toHtml(); ?>
        </a>
        <div class="product details product-item-details">
          <strong class="product name product-item-name"><a class="product-item-link" 
            title="<?= $block->escapeHtml($_item->getName()) ?>" 
            href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                    <?= $block->escapeHtml($_item->getName()) ?></a>
          </strong>
                    <?php if ($slider->getDisplayPrice()): ?>
                        <?= /* @noEscape */ $block->getProductPrice($_item); ?>
            <?php endif ?>
                    <?php if ($templateType): ?>
                        <?= $block->getReviewsSdsmaryHtml($_item, $templateType) ?>
            <?php endif; ?>

                    <?= $block->getProductsliderProductDetailsHtml($_item); ?>

                    <?php if ($showWishlist || $showCompare || $showCart): ?>
        <div class="ds-product-item-inner">
         <div class="product actions product-item-actions">
                        <?php if ($showCart): ?>
         <div class="actions-primary">
                            <?php if ($_item->isSaleable()): ?>
                                <?php if ($enableAjaxcart): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_item); ?>
            <form data-role="tocart-form" 
                  action="<?= $block->escapeUrl($postParams['action']); ?>" 
                  method="post">
                <input type="hidden" name="product" 
                       value="<?= /* @noEscape */ $postParams['data']['product']; ?>">
                <input type="hidden" 
                      name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED; ?>"
                 value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                    <?= $block->getBlockHtml('formkey')?>
                <button type="submit"
                        title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
                        class="action tocart primary">
                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                </button>
            </form>
            <?php else: ?>
                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                <button class="action tocart primary" 
           data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' 
                   type="button" title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                </button>
                <?php else: ?>
                <button class="action tocart primary" 
                    data-post='<?= /* @noEscape */ $block->getAddCartPostParams($_item); ?>'
                        type="button" title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                </button>
                <?php endif; ?>
            <?php endif; ?>
            <?php else: ?>
                <?php if ($_item->getIsSalable()): ?>
                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                <?php else: ?>
                <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                <?php endif; ?>
            <?php endif; ?>
          </div>
        <?php endif; ?>

                        <?php if ($showWishlist || $showCompare): ?>
          <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                            <?php if ($block->isWishlistAllowed() && $showWishlist): ?>
                  <a href="#" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item); ?>'
                       class="action towishlist" data-action="add-to-wishlist" 
                       title="<?= $block->escapeHtml(__('Add to Wish List')) ?>">
                       <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                  </a>
                <?php endif; ?>
                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                  <a href="#" class="action tocompare"
                     data-post='<?= /* @noEscape */ $block->getComparePostDataParams($_item);?>'
                     data-role="add-to-links"
                     title="<?= $block->escapeHtml(__('Add to Compare')); ?>">
                      <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                  </a>
                <?php endif; ?>
          </div>
        <?php endif; ?>
      </div>
    </div> 
    <?php endif; ?>
    </div>
    </div>
                    <?=($iterator == count($collection)+1) ? '</li>' : '' ?>
    <?php endforeach ?>
    <?php endforeach ?>
    </ol>
    </div>
    <?php endif ?>
    </div>
    </div>
   
<?php endif ?>
<script>
require(['jquery', 'owlcarousel'], function($) {
    $(document).ready(function() {
        $('.owl-carousel').owlCarousel({
            loop: true,
            margin: 10,
            dots: true,
            nav: true,
            autoplay: true,
             navText:["<div class='nav-btn prev-slide'></div>","<div class='nav-btn next-slide'></div>"],
            autoplayHoverPause: false,
            responsive: {
                0: {
                  items: 5
                },
                600: {
                  items: 5
                },
                1000: {
                  items: 5
                }
            }
        });
//         $('.owl-carousel').find('.owl-dots').removeClass('disabled');
// $('.owl-carousel').on('changed.owl.carousel', function(event) {
//   $(this).find('.owl-dots').removeClass('disabled');
// });
    });
});
</script>
<style type="text/css">
  button.owl-prev{
  height: 47px;
  position: absolute;
  left: -33px;
  width: 26px;
  cursor: pointer;
  top: 100px !important;
  opacity: 1 !important;
  z-index: 1;
  pointer-events: visible !important;
}
button.owl-next{

  height: 47px;
  position: absolute;
  right: -33px;
  width: 26px;
  cursor: pointer;
  top: 100px !important;
  opacity: 1 !important;
  z-index: 1;
  pointer-events: visible !important;
}
.owl-carousel .owl-prev,
.owl-carousel .owl-next{
pointer-events: none;
opacity: 0.2;
}

.owl-carousel .prev-slide{
  background: url(pub/media/nav.png) no-repeat scroll 0 0;
  background-position: center;
  background-size: 20px;
  width: 20px;
  height: 20px;
}
.owl-carousel .next-slide{
  background: url(pub/media/nav-icon.png) no-repeat scroll -24px 0px;
  background-position: center;
  background-size: 20px;
  width: 20px;
  height: 20px;
}
.owl-carousel .prev-slide:hover{
 background-position: 0px -53px;
}
.owl-carousel .next-slide:hover{
background-position: -24px -53px;
}

</style>